import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// นำเข้า Noto Sans Thai ฟอนต์
const notoSansThai = localFont({
  src: "./fonts/Noto_Sans_Thai/NotoSansThai-VariableFont_wdth,wght.ttf", // แก้ไข src ฟอนต์
  variable: "--font-noto-sans-thai",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansThai.variable} antialiased`}>
        <div className="w-full min-h-screen">
          {children} {/* ย้าย children เข้าไปใน div */}
        </div>
      </body>
    </html>
  );
}
